apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: data-storage
spec:
  project: default
  source:
  - repoURL: oci://registry-1.docker.io/bitnamicharts/minio
    chart: minio
    targetRevision: 17.0.21
    helm:
      valueFiles:
        - $values/helm-values/minio-values.yaml
      timeout: 300
  - repoURL: https://github.com/noah-w24/data-engineering-teil-2.git
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: data-storage
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true