apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://groundhog2k.github.io/helm-charts/
      chart: postgresql
      targetRevision: 1.6.0
      helm:
        valueFiles:
          - $values/helm-values/postgres-values.yaml
    - repoURL: https://github.com/noah-w24/data-engineering-teil-2.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: data-storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true